<%
  if ENV['BEAKER_HYPERVISOR']
    hypervisor = ENV['BEAKER_HYPERVISOR']
  else
    hypervisor = 'vagrant'
  end
-%>
HOSTS:
  el8:
    roles:
      - server
      - default
    platform:   el-8-x86_64
    box:        centos/8
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/8/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
  el7:
    roles:
      - server
    platform:   el-7-x86_64
    box:        centos/7
    hypervisor: <%= hypervisor %>
    yum_repos:
      chef-current:
        baseurl: 'https://packages.chef.io/repos/yum/current/el/7/$basearch'
        gpgkeys:
          - https://packages.chef.io/chef.asc
CONFIG:
  log_level:       verbose
  type:            aio
  vagrant_memsize: 256
<% if ENV['BEAKER_PUPPET_ENVIRONMENT'] -%>
  puppet_environment: <%= ENV['BEAKER_PUPPET_ENVIRONMENT'] %>
<% end -%>
